### PR TITLE
Testing part 1:

### PR DESCRIPTION
**Pull request by annaeliana7**
In this feature, we: 

- Used jest framework for testing
- Create a test file (tasks.test.js) for file containing the add item and delete item functions
- Took a look at each of the functions
- Wrote tests for the pure functions
- Ran tests, with tests passing

### CODE REVIEW

**Comment by annaeliana7** [comment]
Attention: Reviewer, 
Thank you for taking my testing pull request. For some reason there is an issue with the Microverse linters. I tried to delete .github folder and push it again but I'm having the same error. I tried to look for solutions, and it turns out that github stopped using Node 12 which Microverse is using in linters.yml file. The errors that you are seeing here has nothing to do with styling or javascript linter errors. The github actions stops at setup linters for some reasons. Please take this into consideration. Thank you

**Review by Favourezeugwa — COMMENTED** [review]
Hi @annaeliana7 and @Mekuseo , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌❌❌

You have submitted a project, that doesn't have linters passing.

- You can delete the `node-modules` file
- Delete all linters config files (.github/workflows folder, eslintrc.json, hintrc and stylelintrc files) that you have, I'd suggest you go back to the lesson where you learnt about microvers linters installation and download the files for HTML/CSS and JavaScript.
- Then install each of the webhint, stylint and eslint dependencies all over again in your terminal.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by annaeliana7** [comment]
@Favourezeugwa I did that , It doesn't work on github. I deleted files, went to microverse linters repository, downloaded linters . Deleted node_modules, updated my project with the new files.Still having the same error. thank you

**Review by Rustamxon7 — APPROVED** [review]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Developer-512px-10

## Highlights
1. No Linters errors 💯
2. All requirements are complete 💯

## Optional suggestions
No optional suggestions :)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
